/*
Test generated by RoostGPT for test Aayushree-Test using AI Type Open AI and AI Model gpt-4

Test Scenario 1: Empty Message
Validate that the MissingCoordinatesException is thrown when an empty message is passed to the function.

Test Scenario 2: Null Message
Validate that the MissingCoordinatesException is thrown when a null message is passed to the function.

Test Scenario 3: Empty Status
Validate that the MissingCoordinatesException is thrown when an empty status is passed to the function.

Test Scenario 4: Null Status
Validate that the MissingCoordinatesException is thrown when a null status is passed to the function.

Test Scenario 5: Valid Message and Status
Verify that the MissingCoordinatesException is correctly thrown and caught when a valid message and status are passed to the function.

Test Scenario 6: Status Code Verification
Validate that the status code in the MissingCoordinatesException matches the HttpStatus passed to the function.

Test Scenario 7: Message Verification
Validate that the message in the MissingCoordinatesException matches the message passed to the function.

Test Scenario 8: Exception Handling
Verify that the application can correctly handle the MissingCoordinatesException and doesn't crash or hang.

Test Scenario 9: Multiple Exceptions
Validate that the MissingCoordinatesException function can correctly handle multiple exceptions being thrown at the same time.

Test Scenario 10: Exception Message Format
Verify that the message in the MissingCoordinatesException follows the expected format and contains all the necessary information.
*/
import org.springframework.http.HttpStatus;

public class MissingCoordinatesException extends RuntimeException {

    private final HttpStatus status;

    public MissingCoordinatesException(String message, HttpStatus status) {
        super(message);
        this.status = status;
    }

    public HttpStatus getStatus() {
        return status;
    }
}
